config/routes.rb
Pddm2p::Application.routes.draw do
  resources :participants
  resources :sessions,      only: [:new, :create, :destroy]
  resources :commercials
  resources :branches

  
  resources :categories do 
    resources :products
  end 
  
  match '/register',  to: 'participants#receive_android'
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  root :to => 'sessions#new' #'categories#index'
end

app/models/branch.rb
# == Schema Information
#
# Table name: branches
#
#  id         :integer          not null, primary key
#  name       :string(100)
#  street     :string(100)
#  phone      :string(50)
#  delegation :string(100)
#  town       :string(100)
#  state      :string(100)
#

class Branch < ActiveRecord::Base
  attr_accessible :delegation, :name, :state, :street, :town, :phone
end

app/controllers/admin/branches_controller.rb
class Admin::BranchesController < ApplicationController
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
#  before_filter :signed_in_user
  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {branches: @branches} }
    end
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
    @branch = Branch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @branch }
    end
  end

  # GET /branches/new
  # GET /branches/new.json
  def new
    @branch = Branch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @branch }
    end
  end

  # GET /branches/1/edit
  def edit
    @branch = Branch.find(params[:id])
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(params[:branch])

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render json: @branch, status: :created, location: @branch }
      else
        format.html { render action: "new" }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /branches/1
  # PUT /branches/1.json
  def update
    @branch = Branch.find(params[:id])

    respond_to do |format|
      if @branch.update_attributes(params[:branch])
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch = Branch.find(params[:id])
    @branch.destroy

    respond_to do |format|
      format.html { redirect_to branches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/branches_helper.rb
module Admin::BranchesHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= form_for(@branch) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
      <% @branch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Calle %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :Delegacion %><br />
    <%= f.text_field :delegation %>
  </div>
  <div class="field">
    <%= f.label :Estado %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :Municipio %><br />
    <%= f.text_field :town %>
  </div>
  <div class="field">
    <%= f.label :Telefono %><br />
    <%= f.text_field :phone %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h1>Editing branch</h1>

<%= render 'form' %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>

app/views/branches/index.html.erb
<h1>Listing branches</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Calle y No.</th>
    <th>Delegacion</th>
    <th>Estado</th>
    <th>Municipio</th>
    <th>Tel&eacute;fono</th>    
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @branches.each do |branch| %>
  <tr>
    <td><%= branch.name %></td>
    <td><%= branch.street %></td>
    <td><%= branch.delegation %></td>
    <td><%= branch.state %></td>
    <td><%= branch.town %></td>
    <td><%= branch.phone %></td>    
    <td><%= link_to 'Show', branch %></td>
    <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
    <td><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva Sucursal', new_branch_path %>

app/views/branches/new.html.erb
<h1>New branch</h1>

<%= render 'form' %>

<%= link_to 'Back', branches_path %>

app/views/branches/show.html.erb
111111<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @branch.name %>
</p>

<p>
  <b>Calle y N&uacute;mero:</b>
  <%= @branch.street %>
</p>

<p>
  <b>Delegaci&oacute;n:</b>
  <%= @branch.delegation %>
</p>

<p>
  <b>Estado:</b>
  <%= @branch.state %>
</p>

<p>
  <b>Municipio:</b>
  <%= @branch.town %>
</p>

<p>
  <b>Tel&eacute;fono:</b>
  <%= @branch.phone %>
</p>

<%= link_to 'Edit', edit_branch_path(@branch) %> |
<%= link_to 'Back', branches_path %>