config/routes.rb
Pddm2p::Application.routes.draw do
  resources :participants
  resources :sessions,      only: [:new, :create, :destroy]
  resources :commercials
  resources :branches

  
  resources :categories do 
    resources :products
  end 
  
  match '/register',  to: 'participants#receive_android'
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  root :to => 'sessions#new' #'categories#index'
end

app/models/commercial.rb
# == Schema Information
#
# Table name: commercials
#
#  id    :integer          not null, primary key
#  image :string(100)
#  video :string(100)
#

class Commercial < ActiveRecord::Base
  attr_accessible :image, :video
  
  mount_uploader :image, ImageUploader
  mount_uploader :video, ImageUploader
end

app/controllers/admin/commercials_controller.rb
class Admin::CommercialsController < ApplicationController
end

app/controllers/commercials_controller.rb
class CommercialsController < ApplicationController
#  before_filter :signed_in_user
  
  # GET /commercials
  # GET /commercials.json
  def index
    @commercials = Commercial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {commercials: @commercials } }
    end
  end

  # GET /commercials/1
  # GET /commercials/1.json
  def show
    @commercial = Commercial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @commercial }
    end
  end

  # GET /commercials/new
  # GET /commercials/new.json
  def new
    @commercial = Commercial.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @commercial }
    end
  end

  # GET /commercials/1/edit
  def edit
    @commercial = Commercial.find(params[:id])
  end

  # POST /commercials
  # POST /commercials.json
  def create
    @commercial = Commercial.new(params[:commercial])

    respond_to do |format|
      if @commercial.save
        format.html { redirect_to @commercial, notice: 'Commercial was successfully created.' }
        format.json { render json: @commercial, status: :created, location: @commercial }
      else
        format.html { render action: "new" }
        format.json { render json: @commercial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /commercials/1
  # PUT /commercials/1.json
  def update
    @commercial = Commercial.find(params[:id])

    respond_to do |format|
      if @commercial.update_attributes(params[:commercial])
        format.html { redirect_to @commercial, notice: 'Commercial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @commercial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commercials/1
  # DELETE /commercials/1.json
  def destroy
    @commercial = Commercial.find(params[:id])
    @commercial.destroy

    respond_to do |format|
      format.html { redirect_to commercials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/commercials_helper.rb
module Admin::CommercialsHelper
end

app/helpers/commercials_helper.rb
module CommercialsHelper
end

app/views/commercials/_form.html.erb
<%= form_for(@commercial) do |f| %>
  <% if @commercial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commercial.errors.count, "error") %> prohibited this commercial from being saved:</h2>

      <ul>
      <% @commercial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :video %><br />
    <%= f.file_field :video %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commercials/edit.html.erb
<h1>Editing commercial</h1>

<%= render 'form' %>

<%= link_to 'Show', @commercial %> |
<%= link_to 'Back', commercials_path %>

app/views/commercials/index.html.erb
<h1>Listing commercials</h1>

<table class="table">
  <tr>
    <th>Image</th>
    <th>Video</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @commercials.each do |commercial| %>
  <tr>
    <td><%= commercial.image %></td>
    <td><%= commercial.video %></td>
    <td><%= link_to 'Show', commercial %></td>
    <td><%= link_to 'Edit', edit_commercial_path(commercial) %></td>
    <td><%= link_to 'Destroy', commercial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Commercial', new_commercial_path %>

app/views/commercials/new.html.erb
<h1>New commercial</h1>

<%= render 'form' %>

<%= link_to 'Back', commercials_path %>

app/views/commercials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <%= @commercial.image %>
</p>

<p>
  <b>Video:</b>
  <%= @commercial.video %>
</p>


<%= link_to 'Edit', edit_commercial_path(@commercial) %> |
<%= link_to 'Back', commercials_path %>