config/routes.rb
Pddm2p::Application.routes.draw do
  resources :participants
  resources :sessions,      only: [:new, :create, :destroy]
  resources :commercials
  resources :branches

  
  resources :categories do 
    resources :products
  end 
  
  match '/register',  to: 'participants#receive_android'
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  root :to => 'sessions#new' #'categories#index'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Nike", root_path, id: "logo" %>
      <nav>
        <% if signed_in? %>
          <ul class="nav pull-right">
            <li><%= link_to "Categorías de productos", categories_path %></li>
            <li><%= link_to "Sucursales", branches_path %></li>
            <li><%= link_to "Comerciales", commercials_path %></li>
            <li><%= link_to "SMS users", participants_path %></li>
            <li><%= link_to "Signout", signout_path, method: "delete" %></li>
          </ul>
        <% end %>  
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pddm2p</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>